services:
  - type: web
    name: rotating-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROXY_USER
        value: rood  # usr
      - key: PROXY_PASS
        value: rood123  # pss
